ini adalah file bat yang saya buat DODIMAN TAKIMPOO
Press any key to continue . . .

(globalenv) D:\PROGRAMMING\projects-skripsi\sipt\sipt>python manage.py show_urls
/       core.views.main_views.index     core_index
/accounts/api/  rest_framework.routers.APIRootView      api-root
/accounts/api/<drf_format_suffix:format>        rest_framework.routers.APIRootView      api-root
/accounts/api/akuns/    accounts.api.views.AkunListView akuns
/accounts/api/akuns/me/ accounts.api.views.AkunMeView   akuns_me
/accounts/api/profiles/ accounts.api.views.ProfileViewSet       profile-list
/accounts/api/profiles/<pk>/    accounts.api.views.ProfileViewSet       profile-detail
/accounts/api/profiles/<pk>\.<format>/  accounts.api.views.ProfileViewSet       profile-detail
/accounts/api/profiles\.<format>/       accounts.api.views.ProfileViewSet       profile-list
/accounts/api/user-aktif/       accounts.api.views.UserAktifView        accounts_api_user_aktif
/accounts/api/user/     accounts.api.views.UserView     accounts_api_user
/accounts/api/user/<int:user_id>/       accounts.api.views.UserDetailView       accounts_api_user_detail
/accounts/api/users/    accounts.api.views.UserViewSet  user-list
/accounts/api/users/<pk>/       accounts.api.views.UserViewSet  user-detail
/accounts/api/users/<pk>\.<format>/     accounts.api.views.UserViewSet  user-detail
/accounts/api/users\.<format>/  accounts.api.views.UserViewSet  user-list
/accounts/change_password/      accounts.views.change_password  accounts_change_password
/accounts/login/        accounts.views.login_view       accounts_login
/accounts/logout/       accounts.views.logout_view      accounts_logout
/accounts/register/     accounts.views.register accounts_register
/admin/ django.contrib.admin.sites.index        admin:index
/admin/<app_label>/     django.contrib.admin.sites.app_index    admin:app_list
/admin/<url>    django.contrib.admin.sites.catch_all_view
/admin/accounts/profile/        django.contrib.admin.options.changelist_view    admin:accounts_profile_changelist
/admin/accounts/profile/<path:object_id>/       django.views.generic.base.RedirectView
/admin/accounts/profile/<path:object_id>/change/        django.contrib.admin.options.change_view        admin:accounts_profile_change
/admin/accounts/profile/<path:object_id>/delete/        django.contrib.admin.options.delete_view        admin:accounts_profile_delete
/admin/accounts/profile/<path:object_id>/history/       django.contrib.admin.options.history_view       admin:accounts_profile_history
/admin/accounts/profile/add/    django.contrib.admin.options.add_view   admin:accounts_profile_add
/admin/auth/group/      django.contrib.admin.options.changelist_view    admin:auth_group_changelist
/admin/auth/group/<path:object_id>/     django.views.generic.base.RedirectView
/admin/auth/group/<path:object_id>/change/      django.contrib.admin.options.change_view        admin:auth_group_change
/admin/auth/group/<path:object_id>/delete/      django.contrib.admin.options.delete_view        admin:auth_group_delete
/admin/auth/group/<path:object_id>/history/     django.contrib.admin.options.history_view       admin:auth_group_history
/admin/auth/group/add/  django.contrib.admin.options.add_view   admin:auth_group_add
/admin/auth/user/       django.contrib.admin.options.changelist_view    admin:auth_user_changelist
/admin/auth/user/<id>/password/ django.contrib.auth.admin.user_change_password  admin:auth_user_password_change
/admin/auth/user/<path:object_id>/      django.views.generic.base.RedirectView
/admin/auth/user/<path:object_id>/change/       django.contrib.admin.options.change_view        admin:auth_user_change
/admin/auth/user/<path:object_id>/delete/       django.contrib.admin.options.delete_view        admin:auth_user_delete
/admin/auth/user/<path:object_id>/history/      django.contrib.admin.options.history_view       admin:auth_user_history
/admin/auth/user/add/   django.contrib.auth.admin.add_view      admin:auth_user_add
/admin/autocomplete/    django.contrib.admin.sites.autocomplete_view    admin:autocomplete
/admin/jsi18n/  django.contrib.admin.sites.i18n_javascript      admin:jsi18n
/admin/login/   django.contrib.admin.sites.login        admin:login
/admin/logout/  django.contrib.admin.sites.logout       admin:logout
/admin/notification/notification/       django.contrib.admin.options.changelist_view    admin:notification_notification_changelist
/admin/notification/notification/<path:object_id>/      django.views.generic.base.RedirectView
/admin/notification/notification/<path:object_id>/change/       django.contrib.admin.options.change_view        admin:notification_notification_change
/admin/notification/notification/<path:object_id>/delete/       django.contrib.admin.options.delete_view        admin:notification_notification_delete
/admin/notification/notification/<path:object_id>/history/      django.contrib.admin.options.history_view       admin:notification_notification_history
/admin/notification/notification/add/   django.contrib.admin.options.add_view   admin:notification_notification_add
/admin/password_change/ django.contrib.admin.sites.password_change      admin:password_change
/admin/password_change/done/    django.contrib.admin.sites.password_change_done admin:password_change_done
/admin/r/<path:content_type_id>/<path:object_id>/       django.contrib.contenttypes.views.shortcut      admin:view_on_site
/admin/spt/jenissurat/  django.contrib.admin.options.changelist_view    admin:spt_jenissurat_changelist
/admin/spt/jenissurat/<path:object_id>/ django.views.generic.base.RedirectView
/admin/spt/jenissurat/<path:object_id>/change/  django.contrib.admin.options.change_view        admin:spt_jenissurat_change
/admin/spt/jenissurat/<path:object_id>/delete/  django.contrib.admin.options.delete_view        admin:spt_jenissurat_delete
/admin/spt/jenissurat/<path:object_id>/history/ django.contrib.admin.options.history_view       admin:spt_jenissurat_history
/admin/spt/jenissurat/add/      django.contrib.admin.options.add_view   admin:spt_jenissurat_add
/admin/spt/lampiranpermohonanspt/       django.contrib.admin.options.changelist_view    admin:spt_lampiranpermohonanspt_changelist
/admin/spt/lampiranpermohonanspt/<path:object_id>/      django.views.generic.base.RedirectView
/admin/spt/lampiranpermohonanspt/<path:object_id>/change/       django.contrib.admin.options.change_view        admin:spt_lampiranpermohonanspt_change
/admin/spt/lampiranpermohonanspt/<path:object_id>/delete/       django.contrib.admin.options.delete_view        admin:spt_lampiranpermohonanspt_delete
/admin/spt/lampiranpermohonanspt/<path:object_id>/history/      django.contrib.admin.options.history_view       admin:spt_lampiranpermohonanspt_history
/admin/spt/lampiranpermohonanspt/add/   django.contrib.admin.options.add_view   admin:spt_lampiranpermohonanspt_add
/admin/spt/nomorsuratsequence/  django.contrib.admin.options.changelist_view    admin:spt_nomorsuratsequence_changelist
/admin/spt/nomorsuratsequence/<path:object_id>/ django.views.generic.base.RedirectView
/admin/spt/nomorsuratsequence/<path:object_id>/change/  django.contrib.admin.options.change_view        admin:spt_nomorsuratsequence_change
/admin/spt/nomorsuratsequence/<path:object_id>/delete/  django.contrib.admin.options.delete_view        admin:spt_nomorsuratsequence_delete
/admin/spt/nomorsuratsequence/<path:object_id>/history/ django.contrib.admin.options.history_view       admin:spt_nomorsuratsequence_history
/admin/spt/nomorsuratsequence/add/      django.contrib.admin.options.add_view   admin:spt_nomorsuratsequence_add
/admin/spt/permohonanspt/       django.contrib.admin.options.changelist_view    admin:spt_permohonanspt_changelist
/admin/spt/permohonanspt/<path:object_id>/      django.views.generic.base.RedirectView
/admin/spt/permohonanspt/<path:object_id>/change/       django.contrib.admin.options.change_view        admin:spt_permohonanspt_change
/admin/spt/permohonanspt/<path:object_id>/delete/       django.contrib.admin.options.delete_view        admin:spt_permohonanspt_delete
/admin/spt/permohonanspt/<path:object_id>/history/      django.contrib.admin.options.history_view       admin:spt_permohonanspt_history
/admin/spt/permohonanspt/add/   django.contrib.admin.options.add_view   admin:spt_permohonanspt_add
/admin/spt/spt/ django.contrib.admin.options.changelist_view    admin:spt_spt_changelist
/admin/spt/spt/<path:object_id>/        django.views.generic.base.RedirectView
/admin/spt/spt/<path:object_id>/change/ django.contrib.admin.options.change_view        admin:spt_spt_change
/admin/spt/spt/<path:object_id>/delete/ django.contrib.admin.options.delete_view        admin:spt_spt_delete
/admin/spt/spt/<path:object_id>/history/        django.contrib.admin.options.history_view       admin:spt_spt_history
/admin/spt/spt/add/     django.contrib.admin.options.add_view   admin:spt_spt_add
/admin/spt/sptlampiran/ django.contrib.admin.options.changelist_view    admin:spt_sptlampiran_changelist
/admin/spt/sptlampiran/<path:object_id>/        django.views.generic.base.RedirectView
/admin/spt/sptlampiran/<path:object_id>/change/ django.contrib.admin.options.change_view        admin:spt_sptlampiran_change
/admin/spt/sptlampiran/<path:object_id>/delete/ django.contrib.admin.options.delete_view        admin:spt_sptlampiran_delete
/admin/spt/sptlampiran/<path:object_id>/history/        django.contrib.admin.options.history_view       admin:spt_sptlampiran_history
/admin/spt/sptlampiran/add/     django.contrib.admin.options.add_view   admin:spt_sptlampiran_add
/admin/tugas/suratpernyataantugas/      django.contrib.admin.options.changelist_view    admin:tugas_suratpernyataantugas_changelist
/admin/tugas/suratpernyataantugas/<path:object_id>/     django.views.generic.base.RedirectView
/admin/tugas/suratpernyataantugas/<path:object_id>/change/      django.contrib.admin.options.change_view        admin:tugas_suratpernyataantugas_change
/admin/tugas/suratpernyataantugas/<path:object_id>/delete/      django.contrib.admin.options.delete_view        admin:tugas_suratpernyataantugas_delete
/admin/tugas/suratpernyataantugas/<path:object_id>/history/     django.contrib.admin.options.history_view       admin:tugas_suratpernyataantugas_history
/admin/tugas/suratpernyataantugas/add/  django.contrib.admin.options.add_view   admin:tugas_suratpernyataantugas_add
/admin/tugas/tugaspelaksanaan/  django.contrib.admin.options.changelist_view    admin:tugas_tugaspelaksanaan_changelist
/admin/tugas/tugaspelaksanaan/<path:object_id>/ django.views.generic.base.RedirectView
/admin/tugas/tugaspelaksanaan/<path:object_id>/change/  django.contrib.admin.options.change_view        admin:tugas_tugaspelaksanaan_change
/admin/tugas/tugaspelaksanaan/<path:object_id>/delete/  django.contrib.admin.options.delete_view        admin:tugas_tugaspelaksanaan_delete
/admin/tugas/tugaspelaksanaan/<path:object_id>/history/ django.contrib.admin.options.history_view       admin:tugas_tugaspelaksanaan_history
/admin/tugas/tugaspelaksanaan/add/      django.contrib.admin.options.add_view   admin:tugas_tugaspelaksanaan_add
/admin/workflow/disposisi/      django.contrib.admin.options.changelist_view    admin:workflow_disposisi_changelist
/admin/workflow/disposisi/<path:object_id>/     django.views.generic.base.RedirectView
/admin/workflow/disposisi/<path:object_id>/change/      django.contrib.admin.options.change_view        admin:workflow_disposisi_change
/admin/workflow/disposisi/<path:object_id>/delete/      django.contrib.admin.options.delete_view        admin:workflow_disposisi_delete
/admin/workflow/disposisi/<path:object_id>/history/     django.contrib.admin.options.history_view       admin:workflow_disposisi_history
/admin/workflow/disposisi/add/  django.contrib.admin.options.add_view   admin:workflow_disposisi_add
/admin/workflow/disposisitemplate/      django.contrib.admin.options.changelist_view    admin:workflow_disposisitemplate_changelist
/admin/workflow/disposisitemplate/<path:object_id>/     django.views.generic.base.RedirectView
/admin/workflow/disposisitemplate/<path:object_id>/change/      django.contrib.admin.options.change_view        admin:workflow_disposisitemplate_change
/admin/workflow/disposisitemplate/<path:object_id>/delete/      django.contrib.admin.options.delete_view        admin:workflow_disposisitemplate_delete
/admin/workflow/disposisitemplate/<path:object_id>/history/     django.contrib.admin.options.history_view       admin:workflow_disposisitemplate_history
/admin/workflow/disposisitemplate/add/  django.contrib.admin.options.add_view   admin:workflow_disposisitemplate_add
/admin/workflow/sptapproval/    django.contrib.admin.options.changelist_view    admin:workflow_sptapproval_changelist
/admin/workflow/sptapproval/<path:object_id>/   django.views.generic.base.RedirectView
/admin/workflow/sptapproval/<path:object_id>/change/    django.contrib.admin.options.change_view        admin:workflow_sptapproval_change
/admin/workflow/sptapproval/<path:object_id>/delete/    django.contrib.admin.options.delete_view        admin:workflow_sptapproval_delete
/admin/workflow/sptapproval/<path:object_id>/history/   django.contrib.admin.options.history_view       admin:workflow_sptapproval_history
/admin/workflow/sptapproval/add/        django.contrib.admin.options.add_view   admin:workflow_sptapproval_add
/admin/workflow/tandatangan/    django.contrib.admin.options.changelist_view    admin:workflow_tandatangan_changelist
/admin/workflow/tandatangan/<path:object_id>/   django.views.generic.base.RedirectView
/admin/workflow/tandatangan/<path:object_id>/change/    django.contrib.admin.options.change_view        admin:workflow_tandatangan_change
/admin/workflow/tandatangan/<path:object_id>/delete/    django.contrib.admin.options.delete_view        admin:workflow_tandatangan_delete
/admin/workflow/tandatangan/<path:object_id>/history/   django.contrib.admin.options.history_view       admin:workflow_tandatangan_history
/admin/workflow/tandatangan/add/        django.contrib.admin.options.add_view   admin:workflow_tandatangan_add
/api/   rest_framework.routers.APIRootView      spt_api:api-root
/api/<drf_format_suffix:format> rest_framework.routers.APIRootView      spt_api:api-root
/api/permohonan-sptq/   spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-list
/api/permohonan-sptq/<pk>/      spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-detail
/api/permohonan-sptq/<pk>/ajukan-permohonan/    spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-ajukan-permohonan
/api/permohonan-sptq/<pk>/ajukan-permohonan\.<format>/  spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-ajukan-permohonan
/api/permohonan-sptq/<pk>/revisi-permohonan/    spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-revisi-permohonan
/api/permohonan-sptq/<pk>/revisi-permohonan\.<format>/  spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-revisi-permohonan
/api/permohonan-sptq/<pk>/setujui-permohonan/   spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-setujui-permohonan
/api/permohonan-sptq/<pk>/setujui-permohonan\.<format>/ spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-setujui-permohonan
/api/permohonan-sptq/<pk>/tolak-permohonan/     spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-tolak-permohonan
/api/permohonan-sptq/<pk>/tolak-permohonan\.<format>/   spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-tolak-permohonan
/api/permohonan-sptq/<pk>\.<format>/    spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-detail
/api/permohonan-sptq\.<format>/ spt.api.viewsets.PermohonanSPTViewSet   spt_api:permohonan-spt-list
/api/spt/<int:spt_id>/cetak/pdf/        spt.api.views.CetakLaporanPelaksaanTugas        spt_api:cetak_pdf
/api/sptq/      spt.api.viewsets.SPTViewSet     spt_api:spt-list
/api/sptq/<pk>/ spt.api.viewsets.SPTViewSet     spt_api:spt-detail
/api/sptq/<pk>/revisi-spt/      spt.api.viewsets.SPTViewSet     spt_api:spt-revisi-spt
/api/sptq/<pk>/revisi-spt\.<format>/    spt.api.viewsets.SPTViewSet     spt_api:spt-revisi-spt
/api/sptq/<pk>/setujui-spt/     spt.api.viewsets.SPTViewSet     spt_api:spt-setujui-spt
/api/sptq/<pk>/setujui-spt\.<format>/   spt.api.viewsets.SPTViewSet     spt_api:spt-setujui-spt
/api/sptq/<pk>/tolak-spt/       spt.api.viewsets.SPTViewSet     spt_api:spt-tolak-spt
/api/sptq/<pk>/tolak-spt\.<format>/     spt.api.viewsets.SPTViewSet     spt_api:spt-tolak-spt
/api/sptq/<pk>\.<format>/       spt.api.viewsets.SPTViewSet     spt_api:spt-detail
/api/sptq\.<format>/    spt.api.viewsets.SPTViewSet     spt_api:spt-list
/api/tugas/<int:tugas_pelaksanaan_id>/tugas-pelaksanaan/        tugas.api.views.TugasPelaksanaanView    tugas_api:tugas-pelaksanaan
/disposisi/     core.views.main_views.disposisi_list    disposisi_list
/disposisi/<int:disposisi_id>   core.views.main_views.disposisi_detail  disposisi_detail
/htmx/disposisi/        core.views.pegawai_views.disposisi_list_htmx    disposisi_list_htmx
/htmx/permohonan/       core.views.main_views.permohonan_list_htmx      permohonan_list_htmx
/htmx/spt/      core.views.main_views.spt_list_htmx     spt_list_htmx
/kasubag/<int:disposisi_id>/buat-spt/   core.views.kasubag_views.buat_spt_kasubag_view  core_kasubag_buat_spt
/kasubag/<int:spt_id>/review-spt/       spt.services_old.review_spt     core_kasubag_review_spt
/kasubag/approval-spt/  core.views.kasubag_views.approval_spt   core_kasubag_approval_spt
/kasubag/approve/<int:disposisi_id>/    core.views.kasubag_views.approve        core_kasubag_approve
/kasubag/daftar-spt-diajukan/   core.views.kasubag_views.daftar_spt_diajukan    core_kasubag_daftar_spt_diajukan
/kasubag/dashboard/     core.views.kasubag_views.kasubag        core_kasubag_dashboard
/kasubag/disposisi/     core.views.kasubag_views.disposisi      core_kasubag_disposisi
/kasubag/disposisi/<int:disposisi_id>/  core.views.main_views.disposisi_detail  core_kasubag_disposisi_detail
/kasubag/htmx/kasubag-permohonan-spt-list-htmx  core.views.kasubag_views.kasubag_permohonan_spt_list_htmx       kasubag_permohonan_spt_list_htmx
/kasubag/permohonan-spt/        core.views.kasubag_views.kasubag_permohonan_spt core_kasubag_permohonan_spt
/kasubag/permohonan-spt/<int:id>        core.views.kasubag_views.kasubag_permohonan_spt_detail  core_kasubag_permohonan_spt_detail
/kasubag/reject/<int:disposisi_id>/     core.views.kasubag_views.reject core_kasubag_reject
/kasubag/review-permohonan/<int:disposisi_id>/  core.views.kasubag_views.review_permohonan      core_kasubag_review_permohonan
/kasubag/revisi/<int:disposisi_id>/     core.views.kasubag_views.revisi core_kasubag_revisi
/login/ core.views.guest_views.login_view       core_login
/media/<path>   django.views.static.serve
/myspt/api/buat-sptku/<int:permohonan_id>/      spt.spt.api.viewsets.BuatSPTBerdasarkanPermohonan       spt:spt_api:buat_sptku
/myspt/api/hapus-lampiran/<int:lampiran_id>/    spt.spt.api.viewsets.HapusLampiranView  spt:spt_api:hapus_lampiran
/myspt/api/kirim-revisi-spt/<int:spt_id>/       spt.spt.api.viewsets.KirimRevisiSPT     spt:spt_api:kirim_revisi_spt
/myspt/api/list-lampiran/<int:spt_id>/  spt.spt.api.viewsets.ListLampiranView   spt:spt_api:list_lampiran
/myspt/api/revisi-sptku/<int:spt_id>/   spt.spt.api.viewsets.RevisiSPTAPIView   spt:spt_api:revisi_sptku
/myspt/api/simpan-banyak-lampiran/<int:spt_id>/ spt.spt.api.viewsets.SimpanBanyakLampiranView   spt:spt_api:simpan_banyak_lampiran
/myspt/api/terima-sptku/<int:spt_id>/   spt.spt.api.viewsets.TerimaSPTAPIView   spt:spt_api:terima_sptku
/myspt/api/tolak-sptku/<int:spt_id>/    spt.spt.api.viewsets.TolakSPTAPIView    spt:spt_api:tolak_sptku
/myspt/web/<int:disposisi_id>/buat-spt/ spt.spt.web.views.create_spt    spt:spt_web:create_spt
/myspt/web/<int:spt_id>/review/ spt.spt.web.views.review_spt    spt:spt_web:review_spt
/notification/  notification.web.views.index    notification:notification_web:index
/notification/<int:notifikasi_id>/      notification.web.views.detail   notification:notification_web:detail
/notification/api/pesan-dibaca/ notification.api.viewsets.PesanDibacaAPIView    notification:notification_api:pesan_dibaca
/notification/htmx/list/        notification.htmx.views.list_view       notification:notification_htmx:list
/notification/htmx/notifikasi-navbar/   notification.htmx.views.notifikasi_navbar       notification:notification_htmx:notifikasi_navbar
/notification/notifications/<int:notifikasi_id>/        notification.web.views.notification_redirect    notification:notification_web:notification_redirect
/pegawai/<int:spt_id>/edit-revisi/      core.views.pegawai_views.edit_revisi    core_edit_revisi
/pegawai/<int:spt_id>/revisi/   core.views.pegawai_views.spt_revisi     core_spt_revisi
/pegawai/<int:spt_id>/upload-laporan/   core.views.pegawai_views.upload_laporan_oleh_pegawai    core_upload_laporan
/pegawai/account-profile/       core.views.main_views.accounts_profile  accounts_profile
/pegawai/account-profile/edit   core.views.main_views.edit_profile      edit_profile
/pegawai/ajukan-spt/    core.views.pegawai_views.ajukan_spt     core_ajukan_spt
/pegawai/ajukan-spt/<int:spt_id>/       core.views.pegawai_views.kirim_pengajuan        core_kirim_pengajuan
/pegawai/dashboard/     core.views.pegawai_views.pegawai        core_pegawai_dashboard
/pegawai/htmx/grid-card core.views.pegawai_views.grid_card_htmx pegawai_grid_card_htmx
/pegawai/htmx/permohonan-spt-list-htmx  core.views.pegawai_views.permohonan_spt_list_htmx       pegawai_permohonan_spt_list_htmx
/pegawai/htmx/spt-list-diterima-htmx    core.views.pegawai_views.spt_list_diterima_htmx pegawai_spt_list_diterima_htmx
/pegawai/permohonan-spt/        core.views.pegawai_views.permohonan_spt core_permohonan_spt
/pegawai/permohonan-spt/<int:id>        core.views.pegawai_views.permohonan_spt_detail  core_permohonan_spt_detail
/pegawai/permohonan-spt/<int:id>/delete core.views.pegawai_views.permohonan_spt_delete  core_permohonan_spt_delete
/pegawai/spt-detail/<int:spt_id>/       core.views.main_views.spt_detail        core_spt_detail
/pegawai/spt-diterima/  core.views.pegawai_views.spt_diterima   core_spt_diterima
/pegawai/spt-saya/      core.views.pegawai_views.spt_saya       core_spt_saya
/permohonan/    core.views.main_views.permohonan_list   permohonan_list
/permohonan/<int:id>    core.views.main_views.permohonan_detail permohonan_detail
/pimpinan/approval-final/       core.views.pimpinan_views.approval_final        core_pimpinan_approval_final
/pimpinan/approve/<int:disposisi_id>/   core.views.pimpinan_views.approve_pimpinan      core_pimpinan_approve
/pimpinan/dashboard/    core.views.pimpinan_views.pimpinan      core_pimpinan_dashboard
/pimpinan/disposisi/    core.views.pimpinan_views.disposisi_pimpinan    core_pimpinan_disposisi
/pimpinan/disposisi/<int:disposisi_id>/ core.views.pimpinan_views.disposisi_detail_pimpinan     core_pimpinan_disposisi_detail
/pimpinan/htmx/laporan-perjalanan-dinas-htmx    core.views.pimpinan_views.laporan_perjalanan_dinas_htmx pimpinan_laporan_perjalanan_dinas_htmx
/pimpinan/laporan-detail-pimpinan/<int:laporan_id>/     core.views.pimpinan_views.laporan_detail_pimpinan       core_pimpinan_laporan_detail_pimpinan
/pimpinan/laporan-pelaksanaan/  core.views.pimpinan_views.laporan_pelaksanaan   core_pimpinan_laporan_pelaksanaan
/pimpinan/reject/<int:disposisi_id>/    core.views.pimpinan_views.reject_pimpinan       core_pimpinan_reject
/pimpinan/revisi/<int:disposisi_id>/    core.views.pimpinan_views.revisi_pimpinan       core_pimpinan_revisi
/pimpinan/setujui-permohonan/<int:disposisi_id>/        core.views.pimpinan_views.pimpinan_setujui_permohonan_view      core_pimpinan_setujui_permohonan
/pimpinan/ttd/  core.views.pimpinan_views.ttd   core_pimpinan_ttd
/register/      core.views.guest_views.register core_register
/spt-web/permohonan/create/     spt.web.views.permohonan_create spt_web:ajukan_permohonan
/spt/   core.views.main_views.spt_list  spt_list
/spt/<int:spt_id>       core.views.main_views.spt_detail        spt_detail
/spt/<int:spt_id>/      spt.views.detail        spt_detail
/spt/<int:spt_id>/approve-final/        spt.views.approve_final spt_approve_final
/spt/<int:spt_id>/cetak/        spt.views.cetak spt_cetak
/spt/<int:spt_id>/preview/      spt.views.preview       spt_preview
/spt/<int:spt_id>/remove/       spt.views.remove        spt_remove
/spt/<int:spt_id>/revisi/       spt.views.revisi        spt_revisi
/spt/<int:spt_id>/template-pdf/ spt.views.template_pdf  template_pdf
/spt/<int:spt_id>/ttd/  spt.views.ttd   spt_ttd
/spt/<int:spt_id>/update        spt.views.spt_update    spt_update
/spt/<int:spt_id>/upload-lampiran/      spt.views.upload_lampiran       spt_upload_lampiran
/spt/<int:spt_id>/verifikasi/   spt.views.verifikasi    spt_verifikasi
/spt/<int:tugas_pelaksanaan_id>/cetak-surat-pernyataan-tugas/pdf/       spt.views.cetak_surat_pernyataan_tugas  cetak_surat_pernyataan_tugas
/spt/create/    spt.views.spt_create    spt_create
/spt/delete-lampiran/<int:lampiran_id>/ spt.views.delete_lampiran       spt_delete_lampiran
/spt/permohonan/        spt.permohonan.web.views.index  permohonan:permohonan_web:list
/spt/permohonan/<int:permohonan_id>/    spt.permohonan.web.views.detail permohonan:permohonan_web:detail
/spt/permohonan/apii/create-permohonan/ spt.permohonan.api.viewsets.PermohonanApiView   permohonan:permohonan_api:create-permohonan
/spt/permohonan/apii/permohonan-list/   spt.permohonan.api.viewsets.PermohonanSPTListView       permohonan:permohonan_api:permohohan-list
/spt/permohonan/create/ spt.permohonan.web.views.create permohonan:permohonan_web:create
/spt/permohonan/htmx/   spt.permohonan.htmx.views.list_permohonan_view  permohonan:permohonan_htmx:list
/spt/review/    spt.views.review        spt_review
/spt/spt/<int:spt_id>/action/<str:action>       spt.views.spt_action    spt_action
/workflow/disposisi/    workflow.disposisi.web.views.daftar_disposisi   disposisi:disposisi_web:list
/workflow/disposisi/<int:disposisi_id>/ workflow.disposisi.web.views.detail     disposisi:disposisi_web:detail
/workflow/disposisi/api/disposisi/create/       workflow.disposisi.api.viewsets.DisposisiCreateView     disposisi:disposisi_api:disposisi_create
/workflow/disposisi/api/kirim-revisi/<int:disposisi_id>/        workflow.disposisi.api.viewsets.DisposisiUpdateRevisiView       disposisi:disposisi_api:kirim_revisi
/workflow/disposisi/inbox-detail/<int:disposisi_id>/    workflow.disposisi.web.views.inbox_detail       disposisi:disposisi_web:inbox_detail
/workflow/disposisi/inbox/      workflow.disposisi.web.views.inbox      disposisi:disposisi_web:inbox

(globalenv) D:\PROGRAMMING\projects-skripsi\sipt\sipt>