# Generated by Django 5.2.3 on 2026-05-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notification", "0002_alter_notification_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="disposisi",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="permohonan",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="spt",
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
