# Generated by Django 5.2.3 on 2026-04-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_spt", models.CharField(max_length=100)),
                ("judul", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True)),
                ("tanggal_mulai", models.DateField()),
                ("tanggal_selesai", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("diajukan", "Diajukan"),
                            ("disetujui", "Disetujui"),
                            ("ditolak", "Ditolak"),
                            ("direvisi", "Direvisi"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dibuat_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spt_dibuat",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPTLampiran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="lampiran_spt/")),
                ("keterangan", models.CharField(blank=True, max_length=255)),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lampiran",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
    ]
