# Generated by Django 5.2.3 on 2026-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spt",
            name="catatan",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
