# Generated by Django 5.2.3 on 2026-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0002_spt_catatan"),
    ]

    operations = [
        migrations.CreateModel(
            name="NomorSuratSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.IntegerField()),
                ("bulan", models.IntegerField()),
                ("nomor_akhir", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("tahun", "bulan")},
            },
        ),
    ]
