# Generated by Django 5.2.3 on 2026-04-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0003_nomorsuratsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermohonanSPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("permohonan_diajukan", "Permohonan Diajukan"),
                            ("KASUBAG_REVIEW", "Kasubag Review"),
                            ("KASUBAG_SETUJUI", "Kasubag Setujui"),
                            ("kasubag_ajukan_spt", "Kasubag Ajukan SPT"),
                            ("KEPALA_REVIEW_PERMOHONAN", "Kepala Review Permohonan"),
                            ("KEPALA_SETUJUI_PERMOHONAN", "Kepala Setujui Permohonan"),
                            ("SPT_DIBUAT", "SPT Dibuat"),
                            ("KEPALA_REVIEW_SPT", "Kepala Review SPT"),
                            ("KEPALA_SETUJUI_SPT", "Kepala Setujui SPT"),
                            ("TTD_SPT", "Tanda Tangan SPT"),
                            ("DITOLAK", "Ditolak"),
                            ("diajukan", "diajukan"),
                            ("disetujui", "disetujui"),
                            ("final", "final"),
                            ("selesai", "selesai"),
                            ("revisi", "revisi"),
                            ("review_kasubbag", "review_kasubbag"),
                            ("revisi_kasubbag", "revisi_kasubbag"),
                            ("disetujui_final", "disetujui_final"),
                            ("ditolak_pimpinan", "ditolak_pimpinan"),
                            ("revisi_pimpinan", "revisi_pimpinan"),
                            ("review_pimpinan", "review_pimpinan"),
                            ("ditolak_kasubbag", "ditolak_kasubbag"),
                            ("diajukan_ulang", "diajukan_ulang"),
                            ("pelaksanaan", "pelaksanaan"),
                            (
                                "permohonan_disetujui_pimpinan",
                                "permohonan_disetujui_pimpinan",
                            ),
                            ("review_spt_pimpinan", "review_spt_pimpinan"),
                        ],
                        default="draft",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permohonan_spt",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
    ]
