# Generated by Django 5.2.3 on 2026-05-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0005_alter_permohonanspt_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="permohonanspt",
            name="deskripsi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permohonanspt",
            name="dibuat_oleh",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permohonan_spt",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="permohonanspt",
            name="judul",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="permohonanspt",
            name="tanggal_mulai",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permohonanspt",
            name="tanggal_selesai",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LampiranPermohonanSPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="lampiran_permohonan_spt/")),
                ("keterangan", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "permohonan_spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lampiran",
                        to="spt.permohonanspt",
                    ),
                ),
            ],
        ),
    ]
