# Generated by Django 5.2.3 on 2026-05-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0006_permohonanspt_deskripsi_permohonanspt_dibuat_oleh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permohonanspt",
            name="catatan",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
