# Generated by Django 5.2.3 on 2026-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0007_permohonanspt_catatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permohonanspt",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("permohonan_diajukan", "Permohonan Diajukan"),
                    ("KASUBAG_REVIEW", "Kasubag Review"),
                    ("KASUBAG_SETUJUI", "Kasubag Setujui"),
                    ("KASUBAG_SETUJUI_PERMOHOAN", "Kasubag Setujui Permohonan"),
                    ("kasubag_ajukan_spt", "Kasubag Ajukan SPT"),
                    ("KEPALA_REVIEW_PERMOHONAN", "Kepala Review Permohonan"),
                    ("KEPALA_SETUJUI_PERMOHONAN", "Kepala Setujui Permohonan"),
                    ("SPT_DIBUAT", "SPT Dibuat"),
                    ("KEPALA_REVIEW_SPT", "Kepala Review SPT"),
                    ("KEPALA_SETUJUI_SPT", "Kepala Setujui SPT"),
                    ("TTD_SPT", "Tanda Tangan SPT"),
                    ("ditolak", "Ditolak"),
                    ("diajukan", "diajukan"),
                    ("disetujui", "disetujui"),
                    ("final", "final"),
                    ("selesai", "selesai"),
                    ("revisi", "revisi"),
                    ("review_kasubbag", "review_kasubbag"),
                    ("revisi_kasubbag", "revisi_kasubbag"),
                    ("disetujui_final", "disetujui_final"),
                    ("ditolak_pimpinan", "ditolak_pimpinan"),
                    ("revisi_pimpinan", "revisi_pimpinan"),
                    ("review_pimpinan", "review_pimpinan"),
                    ("ditolak_kasubbag", "ditolak_kasubbag"),
                    ("diajukan_ulang", "diajukan_ulang"),
                    ("pelaksanaan", "pelaksanaan"),
                    ("permohonan_disetujui_pimpinan", "permohonan_disetujui_pimpinan"),
                    ("review_spt_pimpinan", "review_spt_pimpinan"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
    ]
