# Generated by Django 5.2.3 on 2026-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0009_jenissurat_alter_permohonanspt_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sptlampiran",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="sptlampiran",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
