# Generated by Django 5.2.3 on 2026-05-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0010_sptlampiran_created_at_sptlampiran_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permohonanspt",
            options={"ordering": ["-created_at"]},
        ),
    ]
