# Generated by Django 5.2.3 on 2026-06-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0011_alter_permohonanspt_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuratPernyataan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surat_pernyataan",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
    ]
