# Generated by Django 5.2.3 on 2026-06-29 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0012_suratpernyataan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suratpernyataan",
            name="spt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surat_pernyataan",
                to="spt.spt",
            ),
        ),
    ]
