# Generated by Django 5.2.3 on 2026-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
