# Generated by Django 5.2.3 on 2026-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_nama"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ttd",
            field=models.ImageField(blank=True, null=True, upload_to="ttd/"),
        ),
    ]
