# Generated by Django 5.2.3 on 2026-04-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_ttd"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pangkat",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="unit_kerja",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
