# Generated by Django 5.2.3 on 2026-04-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spt", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TugasPelaksanaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laporan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("belum", "Belum"),
                            ("proses", "Proses"),
                            ("selesai", "Selesai"),
                        ],
                        default="belum",
                        max_length=20,
                    ),
                ),
                (
                    "pegawai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tugas_dikerjakan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tugas",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
    ]
