# Generated by Django 5.2.3 on 2026-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tugaspelaksanaan",
            name="hasil",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="tugaspelaksanaan",
            name="keterangan",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
