# Generated by Django 5.2.3 on 2026-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0002_tugaspelaksanaan_hasil_tugaspelaksanaan_keterangan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tugaspelaksanaan",
            name="lampiran",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="lampiran_tugas/"
            ),
        ),
    ]
