# Generated by Django 5.2.3 on 2026-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0003_tugaspelaksanaan_lampiran"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tugaspelaksanaan",
            name="lampiran",
            field=models.FileField(blank=True, null=True, upload_to="lampiran_tugas/"),
        ),
    ]
