# Generated by Django 5.2.3 on 2026-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0004_alter_tugaspelaksanaan_lampiran"),
    ]

    operations = [
        migrations.AddField(
            model_name="tugaspelaksanaan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tugaspelaksanaan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
