# Generated by Django 5.2.3 on 2026-05-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0005_tugaspelaksanaan_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuratPernyataanPimpinan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surat_pernyataan",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tugas_pelaksanaan",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tugas.tugaspelaksanaan",
                    ),
                ),
            ],
        ),
    ]
