# Generated by Django 5.2.3 on 2026-05-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0006_suratpernyataanpimpinan"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SuratPernyataanPimpinan",
            new_name="SuratPernyataanTugas",
        ),
    ]
