# Generated by Django 5.2.3 on 2026-05-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0007_rename_suratpernyataanpimpinan_suratpernyataantugas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suratpernyataantugas",
            name="tugas_pelaksanaan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surat_pernyataan",
                to="tugas.tugaspelaksanaan",
            ),
        ),
    ]
