# Generated by Django 5.2.3 on 2026-05-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0008_alter_suratpernyataantugas_tugas_pelaksanaan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suratpernyataantugas",
            name="tugas_pelaksanaan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surat_pernyataan_tugas",
                to="tugas.tugaspelaksanaan",
            ),
        ),
    ]
