# Generated by Django 5.2.3 on 2026-05-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas", "0009_alter_suratpernyataantugas_tugas_pelaksanaan"),
    ]

    operations = [
        migrations.AddField(
            model_name="suratpernyataantugas",
            name="no_surat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="suratpernyataantugas",
            name="tanggal",
            field=models.DateField(blank=True, null=True),
        ),
    ]
