# Generated by Django 5.2.3 on 2026-04-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spt", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disposisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("diajukan", "Diajukan"),
                            ("disetujui", "Disetujui"),
                            ("ditolak", "Ditolak"),
                        ],
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dari_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposisi_dikirim",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ke_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposisi_diterima",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposisi",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPTApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setuju", "Setuju"),
                            ("tolak", "Tolak"),
                            ("revisi", "Revisi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("catatan", models.TextField(blank=True)),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_diberikan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="spt.spt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TandaTangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipe",
                    models.CharField(
                        choices=[("spt", "SPT"), ("disposisi", "Disposisi")],
                        max_length=20,
                    ),
                ),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                (
                    "spt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanda_tangan",
                        to="spt.spt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanda_tangan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
