# Generated by Django 5.2.3 on 2026-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposisiTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipe",
                    models.CharField(
                        choices=[
                            ("instruksi", "instruksi"),
                            ("info", "info"),
                            ("request", "request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("teks_default", models.TextField()),
            ],
        ),
    ]
