# Generated by Django 5.2.3 on 2026-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_disposisitemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposisitemplate",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("instruksi", "instruksi"),
                    ("info", "info"),
                    ("request", "request"),
                    ("revisi", "revisi"),
                ],
                max_length=20,
            ),
        ),
    ]
