# Generated by Django 5.2.3 on 2026-05-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spt", "0009_jenissurat_alter_permohonanspt_status_and_more"),
        ("workflow", "0003_alter_disposisitemplate_tipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposisi",
            name="catatan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disposisi",
            name="spt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disposisi",
                to="spt.spt",
            ),
        ),
        migrations.AlterField(
            model_name="disposisi",
            name="status",
            field=models.CharField(
                choices=[
                    ("instruksi", "instruksi"),
                    ("info", "info"),
                    ("request", "request"),
                    ("revisi", "revisi"),
                ],
                max_length=20,
            ),
        ),
    ]
