# Generated by Django 5.2.3 on 2026-05-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_alter_disposisi_catatan_alter_disposisi_spt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposisi",
            name="status",
            field=models.CharField(
                choices=[
                    ("instruksi", "instruksi"),
                    ("info", "info"),
                    ("request", "request"),
                    ("revisi", "revisi"),
                    ("selesai", "selesai"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="disposisitemplate",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("instruksi", "instruksi"),
                    ("info", "info"),
                    ("request", "request"),
                    ("revisi", "revisi"),
                    ("selesai", "selesai"),
                ],
                max_length=20,
            ),
        ),
    ]
